### ISSUE TITLE
adf-login-demo exception at startup

### ISSUE THREAD

**Issue by fcorti** [Alfresco/adf-examples#6]
`adf@adf:~/Desktop/adf-login-demo$ npm start

> ng2-alfresco-login-demo@0.1.0 start /home/adf/Desktop/adf-login-demo
> npm run webpack-dev-server -- --config config/webpack.prod.js --progress  --content-base app/

> ng2-alfresco-login-demo@0.1.0 webpack-dev-server /home/adf/Desktop/adf-login-demo
> node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js "--config" "config/webpack.prod.js" "--progress" "--content-base" "app/"

/home/adf/Desktop/adf-login-demo/node_modules/webpack-dev-server/bin/webpack-dev-server.js:366
		throw e;
		^

TypeError: arguments[i].apply is not a function
    at Compiler.apply (/home/adf/Desktop/adf-login-demo/node_modules/tapable/lib/Tapable.js:306:16)
    at webpack (/home/adf/Desktop/adf-login-demo/node_modules/webpack/lib/webpack.js:32:19)
    at startDevServer (/home/adf/Desktop/adf-login-demo/node_modules/webpack-dev-server/bin/webpack-dev-server.js:360:14)
    at processOptions (/home/adf/Desktop/adf-login-demo/node_modules/webpack-dev-server/bin/webpack-dev-server.js:317:3)
    at Object.<anonymous> (/home/adf/Desktop/adf-login-demo/node_modules/webpack-dev-server/bin/webpack-dev-server.js:441:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

npm ERR! Linux 4.4.0-83-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "webpack-dev-server" "--" "--config" "config/webpack.prod.js" "--progress" "--content-base" "app/"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ng2-alfresco-login-demo@0.1.0 webpack-dev-server: `node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js "--config" "config/webpack.prod.js" "--progress" "--content-base" "app/"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ng2-alfresco-login-demo@0.1.0 webpack-dev-server script 'node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js "--config" "config/webpack.prod.js" "--progress" "--content-base" "app/"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-alfresco-login-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js "--config" "config/webpack.prod.js" "--progress" "--content-base" "app/"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-alfresco-login-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-alfresco-login-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/adf/Desktop/adf-login-demo/npm-debug.log

npm ERR! Linux 4.4.0-83-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ng2-alfresco-login-demo@0.1.0 start: `npm run webpack-dev-server -- --config config/webpack.prod.js --progress  --content-base app/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ng2-alfresco-login-demo@0.1.0 start script 'npm run webpack-dev-server -- --config config/webpack.prod.js --progress  --content-base app/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-alfresco-login-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run webpack-dev-server -- --config config/webpack.prod.js --progress  --content-base app/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-alfresco-login-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-alfresco-login-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/adf/Desktop/adf-login-demo/npm-debug.log
`

**Comment by fcorti** [comment]
After npm install, the npm start throws the exception above.
Any idea or suggested fix?

**Comment by eromano** [comment]
solved

**Comment by fcorti** [comment]
> ng2-alfresco-login-demo@0.1.0 start /home/adf/Desktop/adf-login-demo
> npm run webpack-dev-server -- --config config/webpack.prod.js --progress  --content-base app/


> ng2-alfresco-login-demo@0.1.0 webpack-dev-server /home/adf/Desktop/adf-login-demo
> node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js "--config" "config/webpack.prod.js" "--progress" "--content-base" "app/"

module.js:471
    throw err;
    ^

Error: Cannot find module '/home/adf/Desktop/adf-login-demo/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

**Comment by damian-lewkowicz** [comment]
Just replace all "^" to "~" in package.json file :)
I have no time to submit a patchset, but you can find working package.json here: [package_json.txt](https://github.com/Alfresco/adf-examples/files/1833450/package_json.txt) (rename it to package.json)
